### ISSUE TITLE
[Q] Hello, I have some questions

### ISSUE THREAD

**Issue by trsh** [planaria/dmc#2]
Can you tell a bit more about your project? What features does it include, what is probably missing (sharp edge preservation?). For example I don't see QEF's being used, what is pointed out in the doc. Thank you!

**Comment by planaria** [comment]
Hello,
This project includes sharp edge preservation, but doesn't include sliver elimination.

QEF is a function used only for optimization.
The following line calculate optimization based on QEF.
https://github.com/planaria/dmc/blob/master/include/dmc/tree.hpp#L197

I remembered that I used modified function because I could not calculate practical poinit by using the original QEF in the article.
I could be wrong.

Thank you.

**Comment by trsh** [comment]
@planaria thank you for getting back!  

The "sliver elimination"- how hard would be to apply it  to your code?

For QEF this line you pointed out: `Eigen::Matrix<scalar_type, 4, 1> x = a.jacobiSvd(Eigen::ComputeFullU | Eigen::ComputeFullV).solve(b);` ? Can you bit explain how it works and what it does?

**Comment by planaria** [comment]
Sorry, I don't know the detail about sliver elimination other than what is written in the paper.

This line solves least squares method to minimize QEF.
https://eigen.tuxfamily.org/dox/group__LeastSquares.html
